routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('home.index');

Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register')->name('register.post');
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login')->name('login.post');
Route::resource('article', 'ArticleController', ['only' => ['show']]);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    Route::resource('article.reply', 'ArticleReplyController', ['only' => ['store', 'destroy', 'edit', 'update']]);
    Route::resource('user.article', 'UserArticleController');
    Route::resource('user.notification', 'UserNotificationController', ['only' => ['index']]);
    Route::resource('user', 'UserController');
});

resources/views/article.blade.php
@extends('layout')

@section('header_title')
文章详情
@endsection

@section('content')
<h2>{{ $article->title }}</h2>
<h3>{{ $article->created_at }}</h3>
<div>
{{ $article->content }}
</div>
<div>
<h4>回复列表</h4>
<ul>
	@foreach($replies as $reply)
        <p>{{ $reply->user->name }}</p>
        <p>{{ $reply->created_at }}</p>
        <p>{{ $reply->content }}</p>
        @if(Auth::check() && Auth::user()->id == $reply->user->id)
        	<p><a href="{{ route('article.reply.edit', [$articleId, $reply->id]) }}">编辑</a></p>
        	{!! Form::open(['route' => ['article.reply.destroy', $articleId, $reply->id], 'method' => 'DELETE']) !!}
            <input type="submit" value="删除">
            {!! Form::close() !!}
        @endif
	@endforeach
</ul>
</div>
<div>
@if(Auth::check())
<h4>发表回复</h4>
     {!! Form::open(['route' => ['article.reply.store', $article], 'method' => 'POST']) !!}
        {!! Form::textarea('content', null, ['placeholder' => '请输入回复']); !!}
        {!! $errors->first('content', '<div>:message</div>') !!}
         <input type="submit" value="发表">
    {!! Form::close() !!}
</div>
@else
<p><a href="{{ route('login') }}">登陆</a>后可发表回复</p>
@endif
@endsection

resources/views/home.blade.php
@extends('layout')

@section('header_title')
首页
@endsection

@section('content')
<h2>文章列表</h2>
<div>
<ul>
    @foreach($articles as $article)
        <li>
            <h3><a href="{{ route('article.show', $article) }}">{{ $article->title }}</a></h3>
            <p><img src="{{ $article->user->avatar }}" width="100" height="100"></p>
            <p>{{ $article->user->name }}</p>
            <p>{{ $article->created_at }}</p>
        </li>
    @endforeach
</ul>
</div>
<div class="inner">
    {{ $articles->appends(Request::except('page'))->links() }}
</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>多人博客 - @yield('header_title', '')</title>
    </head>
    <body>
        <h1>多人博客</h1>
        <div>
            <ul>
                <li><a href="{{ route('home.index') }}">首页</a></li>
                @if (Auth::check())
                    <li><a href="{{ route('user.article.create', Auth::user()) }}">发表文章</a></li>
                    <li><a href="{{ route('user.article.index', Auth::user()) }}">我的文章</a></li>
                    <li><a href="{{ route('user.notification.index', Auth::user()) }}">我的消息</a></li>
                    <li><a href="{{ route('user.edit', Auth::user()) }}">我的资料</a></li>
                    <li><a href="{{ route('logout') }}">登出</a></li>
                @else
                    <li><a href="{{ route('login') }}">登录</a></li>
                    <li><a href="{{ route('register') }}">注册</a></li>
                @endif
            </ul>
        </div>
        <div class="content">
            @yield('content')
        </div>
    </body>
</html>

resources/views/notification.blade.php
@extends('layout')

@section('header_title')
我的消息
@endsection

@section('content')
<h2>我的消息</h2>
<div>
<ul>
    @foreach($notifications as $notification)
        <li>
            <p><a href="{{ route('article.show', $notification['data']['article_id']) }}">{{ $notification['data']['user']['name'] }}回复了你</p>
        </li>
    @endforeach
</ul>
</div>
<div class="inner">
    {{ $notifications->appends(Request::except('page'))->links() }}
</div>
@endsection