routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('home.index');

Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register')->name('register.post');
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login')->name('login.post');
Route::resource('article', 'ArticleController', ['only' => ['show']]);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    Route::resource('article.reply', 'ArticleReplyController', ['only' => ['store', 'destroy', 'edit', 'update']]);
    Route::resource('user.article', 'UserArticleController');
    Route::resource('user.notification', 'UserNotificationController', ['only' => ['index']]);
    Route::resource('user', 'UserController');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'content',
        'title',
        'user_id',
        'category_id',
    ];

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;

class ArticleController extends Controller
{
    private $article;

    public function __construct(Article $article)
    {
        $this->article = $article;
    }

    public function show($articleId)
    {
        $article = $this->article->findOrFail($articleId);
        $replies = $article->replies()->paginate(10);

        return view('article', compact('article', 'replies', 'articleId'));
    }
}

resources/views/article/form.blade.php
@extends('layout')

@section('header_title')
$header_title
@endsection

@section('content')
<h2>{{ $header_title }}</h2>
<div>
    <div>
        @if (Route::currentRouteName() === 'user.article.create')
            {!! Form::open(['route' => ['user.article.store', $userId], 'method' => 'POST']) !!}
        @else
            {!! Form::Model($article, ['route' => ['user.article.update', $userId, $article], 'method' => 'PUT']) !!}
        @endif
        <div>
            {{ Form::label('title', '标题') }}
            <div>
                {!! Form::text('title', null, ['placeholder' => '请填写百科知识标题']); !!}
                {!! $errors->first('title', '<div>:message</div>') !!}
            </div>
        </div>
        <div>
            {{ Form::label('category_id', '分类') }}
            <div>
                {!! Form::select('category_id', $categories, null, ['placeholder' => '请选择分类']); !!}
                {!! $errors->first('category_id', '<div>:message</div>') !!}
            </div>
        </div>
        <div>
            {{ Form::label('content', '详细内容') }}
            <div>
                {!! Form::textarea('content', null, ['placeholder' => '请填详细内容']); !!}
                {!! $errors->first('content', '<div>:message</div>') !!}
            </div>
        </div>
    </div>
    <div>
        @if (Route::currentRouteName() === 'user.article.create')
            <input type="submit" value="创建">
        @else
            <input type="submit" value="更新">
        @endif
    </div>
    {!! Form::close() !!}
</div>
@endsection

resources/views/article/index.blade.php
@extends('layout')

@section('header_title')
我的文章
@endsection

@section('content')
<h2>文章列表</h2>
<div>
<ul>
    @foreach($articles as $article)
        <li>
            <h3>{{ $article->title }}</h3>
            <p>{{ $article->created_at }}</p>
            <p><a href="{{ route('user.article.edit', [$userId, $article->id]) }}">编辑</a></p>
            {!! Form::open(['route' => ['user.article.destroy', $userId, $article], 'method' => 'DELETE']) !!}
            <input type="submit" value="删除">
            {!! Form::close() !!}
        </li>
    @endforeach
</ul>
</div>
<div class="inner">
    {{ $articles->appends(Request::except('page'))->links() }}
</div>
@endsection

resources/views/article/reply.blade.php
@extends('layout')

@section('header_title')
编辑回复
@endsection

@section('content')
<h2>编辑回复</h2>
<div>
    <div>
        {!! Form::Model($reply, ['route' => ['article.reply.update', $articleId, $reply], 'method' => 'PUT']) !!}
        <div>
            <div>
                {!! Form::textarea('content', null, ['placeholder' => '请输入回复详情']); !!}
                {!! $errors->first('content', '<div>:message</div>') !!}
            </div>
        </div>
    </div>
    <div>
        <input type="submit" value="更新">
    </div>
    {!! Form::close() !!}
</div>
@endsection